# Change these first
owner: bardsoftware # Your GitHub username
repo: ganttproject-status # Your GitHub repository name

# Add your sites here
sites:
  - name: GanttProject Cloud
    url: https://ganttproject.cloud
  - name: GanttProject Desktop web site
    url: https://www.ganttproject.biz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ganttproject.cloud
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://pbs.twimg.com/profile_images/1308128634687959040/AIKumOpj_400x400.jpg
  name: GanttProject Status
  introTitle: "GanttProject Monitoring"
  introMessage: "This page shows the basic monitoring charts, ongoing incidents, if any, and the incident history"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
